### ISSUE TITLE
Shellsort schneller als Quick ? 

### ISSUE THREAD

**Issue by ErDevDev** [KnutZuidema/ADS#2]
# Issue Template

##### OS/Platform:
<answer> Linux  

##### Compiler:
<answer>  gcc

##### I have altered the source:
<answer>

##### Exact command to reproduce:
<answer>

**Comment by ErDevDev** [comment]
Warum ist dein Shellsort schneller als dein Quicksort ?

**Comment by KnutZuidema** [comment]
Ist es nicht, daß lag an einem Bug. Die Grafik ist nicht aktuell.
