### ISSUE TITLE
delivery

### ISSUE THREAD

**Issue by frzifus** [KnutZuidema/ADS#3]
# Issue Template
Some people have complained that this solution has already been presented. Is it possible to personalize the code automatically? Something like snipping different patterns with clang format and interchangeable code?

##### OS/Platform:
Linux

##### Compiler:
clang

##### I have altered the source:
no

**Comment by KnutZuidema** [comment]
I'm not sure what you mean. Could you expand on your request? Which solution? All of them? Where has what been presented? What does "snipping different patterns with clang format and interchangeable code" constitute?
